[package]
name = "program-translation"
version = "0.1.0"
edition = "2021"
authors = ["Brian Smith"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0"
colored = "2"
