[package]
name = "proc_macros"
version = "0.1.0"
edition = "2021"
authors = ["Brian Smith"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "*"
quote = "*"
proc-macro2 = "*"

[lib]
proc-macro = true
